name: ScanCentral SAST Scan

on: [workflow_dispatch]

jobs:
  ScanCentral-SAST-Scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: fortify/gha-setup-scancentral-client@v2
        with:
          client-auth-token: 15d4af11-4107-4edf-96f9-71f69e79fc67
      - run: scancentral -url http://13.209.176.153:8081/scancentral-ctrl start -bt mvn
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: scancentral-logs
          path: ~/.fortify/scancentral/log

          
